### ISSUE TITLE
Add Poison 4.0 as optional dependency in `mix.exs`?

### ISSUE THREAD

**Issue by dcaixinha** [salemove/logstash_logger_formatter#4]
Hey all,

In [this line](https://github.com/salemove/logstash_logger_formatter/blob/master/mix.exs#L50) we're "locking" `Poison` to either one of these versions, which makes it unusable if in an application we want to use `Poison >= 4.0`. Is it possible to add `4.0` as well? :pray: 

Thanks for the work on this library :raised_hands:

**Comment by take-five** [comment]
Hi @dcaixinha 

Thanks for the report. I'll release the new version as soon as [PR](https://github.com/salemove/logstash_logger_formatter/pull/5) is reviewed and approved 😉 

Out of curiosity... Have you considered switching to [Jason](https://github.com/michalmuskala/jason)?

It is very easy, and Jason (IMO) is better maintained:

```elixir
config :logger, :logstash_formatter,
  engine: Jason
```

**Comment by take-five** [comment]
Version 0.3.0 with Poison 4.0 support is published on Hex.pm

**Comment by dcaixinha** [comment]
Hey @take-five, thanks for the quick reply :bowing_man: 

I have that in my `config.exs`, but I still get conflicting `Poison` versions when I run `mix deps.get` – particularly when I have some other library that has `:poison, ~> 4.0`. Is there any other change I need to make? Thanks :raised_hands:

**Comment by take-five** [comment]
Ah, I see. Please update `logstash_logger_formatter` to 0.3.0, this should resolve the conflict. Thanks.
